using JorgenHoc.MigrationsWalkthrough;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

// The migrate-on-run pattern from the article's "Option 2: Migration as a Separate Job".
// Reports applied and pending migrations, applies anything pending, then shows the final
// __EFMigrationsHistory — so the console output is the article's `migrations list` and
// history table, produced for real.
//
// The migration FILES under Migrations/ are the actual deliverable: they were generated
// by `dotnet ef migrations add`, one per step of the walkthrough. AddProductSlug is
// hand-edited to backfill data before making the column non-nullable — read it to see
// the customization the article describes.

var config = new ConfigurationBuilder()
    .SetBasePath(AppContext.BaseDirectory)
    .AddJsonFile("appsettings.json")
    .Build();

var connectionString = config.GetConnectionString("LocalDbConnection")
    ?? throw new InvalidOperationException(
        "Connection string 'LocalDbConnection' is missing from appsettings.json.");

var options = new DbContextOptionsBuilder<AppDbContext>()
    .UseSqlServer(connectionString)
    .Options;

using var db = new AppDbContext(options);

if (!await db.Database.CanConnectAsync())
    Console.WriteLine("Database does not exist yet — it will be created by the first migration.");

const string preSlugMigration = "AddIndexOnProductName";
var slugMigration = (await db.Database.GetPendingMigrationsAsync())
    .Concat(await db.Database.GetAppliedMigrationsAsync())
    .Single(m => m.EndsWith("AddProductSlug", StringComparison.Ordinal));

Console.WriteLine("Migrations (dotnet ef migrations list):");
foreach (var migration in await db.Database.GetAppliedMigrationsAsync())
    Console.WriteLine($"  {migration} (Applied)");
foreach (var migration in await db.Database.GetPendingMigrationsAsync())
    Console.WriteLine($"  {migration} (Pending)");

var slugAlreadyApplied = (await db.Database.GetAppliedMigrationsAsync()).Contains(slugMigration);
var migrator = db.GetService<IMigrator>();

if (!slugAlreadyApplied)
{
    // Tell the backfill story honestly: bring the schema up to the state BEFORE Slug
    // exists, insert rows that have a Name but no Slug column yet, THEN apply the
    // AddProductSlug migration so its UPDATE ... SET Slug = ... runs on real data.
    Console.WriteLine();
    Console.WriteLine($"Migrating to {preSlugMigration} (pre-Slug schema)...");
    await migrator.MigrateAsync(preSlugMigration);

    // Insert via raw SQL — the Slug column does not exist yet, so an EF insert (which
    // would include Slug) cannot be used here.
    await db.Database.ExecuteSqlRawAsync("""
        IF NOT EXISTS (SELECT 1 FROM Products)
        INSERT INTO Products (Name, Price, CreatedAt) VALUES
            (N'Mechanical Keyboard', 129.99, SYSUTCDATETIME()),
            (N'USB C Cable', 12.50, SYSUTCDATETIME());
        """);

    Console.WriteLine("Seeded 2 rows, then applying AddProductSlug (backfills Slug)...");
    await migrator.MigrateAsync();
    Console.WriteLine("Migrations complete.");
}
else
{
    await db.Database.MigrateAsync();
    Console.WriteLine();
    Console.WriteLine("Already fully migrated — nothing to apply.");
}

Console.WriteLine();
Console.WriteLine("__EFMigrationsHistory:");
var history = await db.Database
    .SqlQueryRaw<string>(
        "SELECT MigrationId AS [Value] FROM __EFMigrationsHistory ORDER BY MigrationId")
    .ToListAsync();
foreach (var id in history)
    Console.WriteLine($"  {id}");

Console.WriteLine();
Console.WriteLine("Products (Slug backfilled from Name by the AddProductSlug migration):");
var products = await db.Products.AsNoTracking().OrderBy(p => p.Id).ToListAsync();
foreach (var p in products)
    Console.WriteLine($"  {p.Name,-22} -> slug \"{p.Slug}\"");

Console.WriteLine();
Console.WriteLine("Every migration under Migrations/ was generated by the EF tools; only");
Console.WriteLine("AddProductSlug was hand-edited, to backfill before the ALTER to NOT NULL.");

if (!Console.IsInputRedirected)
{
    Console.WriteLine();
    Console.WriteLine("Press any key to exit...");
    Console.ReadKey(intercept: true);
}
